# Generated by Django 3.0.3 on 2020-02-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_testsetversion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsetversion',
            name='url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
